#!/bin/sh

echo "START: write-heat-params"
set +x

arch=$(uname -m)

case "$arch" in
    aarch64)
        ARCH=arm64
        ;;
    x86_64)
        ARCH=amd64
        ;;
    *)
        ARCH=$arch
        ;;
esac

ssh_cmd="ssh -F /srv/magnum/.ssh/config root@localhost"

version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

if version_gt $(echo "$KUBE_TAG" | cut -c 2-) 1.25; then
    LEAD_NODE_ROLE_NAME="control-plane"
else
    LEAD_NODE_ROLE_NAME="master"
fi

# Reconciler defaults — applied when Heat template does not set explicit values.
# CI updates the version on each release. SHA256 is downloaded automatically
# from the release alongside the binary.
RECONCILER_DEFAULT_VERSION="v1.0.0"
RECONCILER_DEFAULT_REPOSITORY="https://github.com/ventus-ag/magnum-bootstrap"
RECONCILER_DEFAULT_BINARY_URL="${RECONCILER_DEFAULT_REPOSITORY}/releases/download/${RECONCILER_DEFAULT_VERSION}/bootstrap"
RECONCILER_VERSION="${RECONCILER_VERSION:-${RECONCILER_DEFAULT_VERSION}}"
RECONCILER_BINARY_URL="${RECONCILER_BINARY_URL:-${RECONCILER_DEFAULT_BINARY_URL}}"
RECONCILER_BINARY_URL_SHA256="${RECONCILER_BINARY_URL_SHA256:-}"
RECONCILER_LOCK_TIMEOUT_SECONDS="${RECONCILER_LOCK_TIMEOUT_SECONDS:-900}"

HEAT_PARAMS=/etc/sysconfig/heat-params

echo "Writing File: $HEAT_PARAMS"
mkdir -p "$(dirname ${HEAT_PARAMS})"
cat << EOF > ${HEAT_PARAMS}
ARCH="$ARCH"
SELINUX_MODE="$SELINUX_MODE"
INSTANCE_NAME="$INSTANCE_NAME"
TIMESTAMP_UPGRADE="$TIMESTAMP_UPGRADE"
IS_UPGRADE="$IS_UPGRADE"
IS_RESIZE="$IS_RESIZE"
METRICS_SERVER_ENABLED="$METRICS_SERVER_ENABLED"
KUBE_API_PUBLIC_ADDRESS="$KUBE_API_PUBLIC_ADDRESS"
KUBE_API_PRIVATE_ADDRESS="$KUBE_API_PRIVATE_ADDRESS"
KUBE_API_PORT="$KUBE_API_PORT"
KUBE_NODE_PUBLIC_IP="$KUBE_NODE_PUBLIC_IP"
KUBE_NODE_IP="$KUBE_NODE_IP"
KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
ENABLE_CINDER="$ENABLE_CINDER"
ETCD_VOLUME="$ETCD_VOLUME"
ETCD_VOLUME_SIZE="$ETCD_VOLUME_SIZE"
DOCKER_VOLUME="$DOCKER_VOLUME"
DOCKER_VOLUME_SIZE="$DOCKER_VOLUME_SIZE"
DOCKER_STORAGE_DRIVER="$DOCKER_STORAGE_DRIVER"
NETWORK_DRIVER="$NETWORK_DRIVER"
FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
FLANNEL_BACKEND="$FLANNEL_BACKEND"
PODS_NETWORK_CIDR="$PODS_NETWORK_CIDR"
PORTAL_NETWORK_CIDR="$PORTAL_NETWORK_CIDR"
ADMISSION_CONTROL_LIST="$ADMISSION_CONTROL_LIST"
ETCD_DISCOVERY_URL="$ETCD_DISCOVERY_URL"
CLUSTER_NETWORK_NAME="$CLUSTER_NETWORK_NAME"
CLUSTER_SUBNET="$CLUSTER_SUBNET"
TLS_DISABLED="$TLS_DISABLED"
KUBE_DASHBOARD_ENABLED="$KUBE_DASHBOARD_ENABLED"
VERIFY_CA="$VERIFY_CA"
CLUSTER_UUID="$CLUSTER_UUID"
MAGNUM_URL="$MAGNUM_URL"
VOLUME_DRIVER="$VOLUME_DRIVER"
REGION_NAME="$REGION_NAME"
HTTP_PROXY="$HTTP_PROXY"
HTTPS_PROXY="$HTTPS_PROXY"
NO_PROXY="$NO_PROXY"
KUBE_TAG="$KUBE_TAG"
CLOUD_PROVIDER_ENABLED="$CLOUD_PROVIDER_ENABLED"
NUMBER_OF_MASTERS="$NUMBER_OF_MASTERS"
KUBE_VERSION="$KUBE_VERSION"
TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
TRUST_ID="$TRUST_ID"
AUTH_URL="$AUTH_URL"
INSECURE_REGISTRY_URL="$INSECURE_REGISTRY_URL"
CONTAINER_INFRA_PREFIX="$CONTAINER_INFRA_PREFIX"
ETCD_LB_VIP="$ETCD_LB_VIP"
DNS_SERVICE_IP="$DNS_SERVICE_IP"
DNS_CLUSTER_DOMAIN="$DNS_CLUSTER_DOMAIN"
CERT_MANAGER_API="$CERT_MANAGER_API"
CA_KEY="$CA_KEY"
KUBELET_OPTIONS="$KUBELET_OPTIONS"
KUBECONTROLLER_OPTIONS="$KUBECONTROLLER_OPTIONS"
KUBEAPI_OPTIONS="$KUBEAPI_OPTIONS"
KUBEPROXY_OPTIONS="$KUBEPROXY_OPTIONS"
OCTAVIA_ENABLED="$OCTAVIA_ENABLED"
KUBE_SERVICE_ACCOUNT_KEY="$KUBE_SERVICE_ACCOUNT_KEY"
KUBE_SERVICE_ACCOUNT_PRIVATE_KEY="$KUBE_SERVICE_ACCOUNT_PRIVATE_KEY"
CA_ROTATION_ID="$CA_ROTATION_ID"
KEYSTONE_AUTH_ENABLED="$KEYSTONE_AUTH_ENABLED"
EXTERNAL_NETWORK_ID="$EXTERNAL_NETWORK_ID"
AUTO_HEALING_ENABLED="$AUTO_HEALING_ENABLED"
AUTO_HEALING_CONTROLLER="$AUTO_HEALING_CONTROLLER"
AUTO_SCALING_ENABLED="$AUTO_SCALING_ENABLED"
MANILA_CSI_ENABLED="$MANILA_CSI_ENABLED"
CINDER_CSI_ENABLED="$CINDER_CSI_ENABLED"
LEAD_NODE_ROLE_NAME="$LEAD_NODE_ROLE_NAME"
MIN_NODE_COUNT="$MIN_NODE_COUNT"
MAX_NODE_COUNT="$MAX_NODE_COUNT"
NODEGROUP_ROLE="$NODEGROUP_ROLE"
NODEGROUP_NAME="$NODEGROUP_NAME"
USE_PODMAN="$USE_PODMAN"
KUBE_IMAGE_DIGEST="$KUBE_IMAGE_DIGEST"
CONTAINER_RUNTIME="$CONTAINER_RUNTIME"
POST_INSTALL_MANIFEST_URL="$POST_INSTALL_MANIFEST_URL"
OS_AUTOUPGRADE_ENABLED="$OS_AUTOUPGRADE_ENABLED"
RECONCILER_VERSION="${RECONCILER_VERSION}"
RECONCILER_BINARY_URL="${RECONCILER_BINARY_URL}"
RECONCILER_BINARY_URL_SHA256="${RECONCILER_BINARY_URL_SHA256}"
RECONCILER_LOCK_TIMEOUT_SECONDS="${RECONCILER_LOCK_TIMEOUT_SECONDS}"
EOF

chown root:root "${HEAT_PARAMS}"
chmod 600 "${HEAT_PARAMS}"

echo "END: write-heat-params"
